[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
cbindgen = "0.27.0"

[lib]
name = "native_rust_helloworld"  # Change this name to whatever you want
crate-type = ["cdylib"]
